# Generated by Django 5.1.3 on 2024-12-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
